#!/bin/sh
# Refresh the design-system bundle from the shipped UI, so Claude Design never
# works from stale tokens. Run from anywhere: sh docs/design-system/tools/sync.sh
#
# tokens.css: ui/src/styles/tokens.css with Tailwind's `@theme {` turned into a
#   plain `:root {` (browsers drop unknown at-rules, which would lose the whole
#   light theme outside a Tailwind build).
# fonts/: the self-hosted woff2 files, with fonts.css made path-relative.
set -eu
here=$(cd "$(dirname "$0")/.." && pwd)
repo=$(cd "$here/../.." && pwd)

{
  printf '/* GENERATED by docs/design-system/tools/sync.sh from ui/src/styles/tokens.css.\n'
  printf '   Do not edit here: change the source and re-run the sync.\n'
  printf '   Only difference: Tailwind @theme is a plain :root block, so this file works without a build. */\n\n'
  sed -e 's/^@theme {/:root {/' -e '/--color-\*: initial;/d' "$repo/ui/src/styles/tokens.css"
} > "$here/tokens.css"

mkdir -p "$here/fonts"
cp "$repo"/ui/public/fonts/*.woff2 "$here/fonts/"
sed 's#url(/fonts/#url(./#g' "$repo/ui/public/fonts/fonts.css" > "$here/fonts/fonts.css"
# tokens.css names "Inter Variable" after "Inter" in --font-sans. It is the same family, so alias
# it to the same files: otherwise Claude Design reports a missing font for that name.
grep "font-family:'Inter'" "$here/fonts/fonts.css" | sed "s/font-family:'Inter'/font-family:'Inter Variable'/" > "$here/fonts/aliases.css"

echo "synced tokens.css and $(ls "$here"/fonts/*.woff2 | wc -l | tr -d ' ') font files into $here"
